// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYFWUxnrhf37CKVhKSRjedwKmAzY6t8WM',
    appId: '1:756462532219:web:5a3603bd13ffe3ef4154de',
    messagingSenderId: '756462532219',
    projectId: 'inovva-estetica',
    authDomain: 'inovva-estetica.firebaseapp.com',
    storageBucket: 'inovva-estetica.appspot.com',
    measurementId: 'G-3ZBGSTTHD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdWXiCA6B0HJq2aaL-l91KZccw_0540VA',
    appId: '1:756462532219:android:53efa41bc8554f354154de',
    messagingSenderId: '756462532219',
    projectId: 'inovva-estetica',
    storageBucket: 'inovva-estetica.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCxJooQcKaruOpvC5juSLnsYBa6VhwgTY',
    appId: '1:756462532219:ios:5f4d5468bc8bf6d34154de',
    messagingSenderId: '756462532219',
    projectId: 'inovva-estetica',
    storageBucket: 'inovva-estetica.appspot.com',
    iosClientId: '756462532219-785vc2grofmdagcomaa6adtp7o64jb0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.innovaEstetica',
  );
}
